### ISSUE TITLE
Skewed images on Partners & Customers page

### ISSUE THREAD

**Issue by emcwhirter-usgs** [usgs/geomag-website#126] opened 2015-11-12 17:02 UTC
All of the images on this page look fine in Chrome, but they are skewed, stretched or partially hidden in Firefox and Internet Explorer.

**Comment by lisa-usgs** [comment] 2016-05-10 14:56
This is a duplicate of #152 that has more description about the issue.

**Closed by lisa-usgs** 2016-05-10 14:56 UTC
